// Complete table configuration: columns, form fields, status options
export const TABLE_CONFIG = {
  routes: {
    icon: '🗺️', label: 'Routes',
    columns: [
      { key: 'route_id',     label: 'ID',          pk: true },
      { key: 'source',       label: 'Source',       mono: true },
      { key: 'destination',  label: 'Destination',  mono: true },
      { key: 'distance_km',  label: 'Distance (km)',mono: true },
      { key: 'duration_hrs', label: 'Duration (h)', mono: true },
      { key: 'status',       label: 'Status',       chip: true },
      { key: 'updated_at',   label: 'Updated' },
    ],
    fields: [
      { key: 'source',       label: 'Source City',  type: 'text',   required: true },
      { key: 'destination',  label: 'Destination',  type: 'text',   required: true },
      { key: 'distance_km',  label: 'Distance (km)',type: 'number', required: true },
      { key: 'duration_hrs', label: 'Duration (hrs)',type:'number', required: true },
      { key: 'status',       label: 'Status',       type: 'select', required: true,
        options: ['active','delayed','cancelled'] },
    ],
  },
  vehicles: {
    icon: '🚌', label: 'Vehicles',
    columns: [
      { key: 'vehicle_id', label: 'ID',         pk: true },
      { key: 'vehicle_no', label: 'Vehicle No', mono: true },
      { key: 'type',       label: 'Type' },
      { key: 'capacity',   label: 'Capacity',   mono: true },
      { key: 'operator',   label: 'Operator' },
      { key: 'status',     label: 'Status',     chip: true },
    ],
    fields: [
      { key: 'vehicle_no', label: 'Vehicle Number', type: 'text',   required: true, hint: 'e.g. TS09AB1234' },
      { key: 'type',       label: 'Type',            type: 'select', required: true,
        options: ['Sleeper AC','Semi-Sleeper','Volvo AC','Ordinary','Luxury AC','Sleeper'] },
      { key: 'capacity',   label: 'Capacity',        type: 'number', required: true },
      { key: 'operator',   label: 'Operator',        type: 'text',   required: true },
      { key: 'status',     label: 'Status',          type: 'select', required: true,
        options: ['active','delayed','maintenance'] },
    ],
  },
  schedules: {
    icon: '🕐', label: 'Schedules',
    columns: [
      { key: 'schedule_id',   label: 'ID',          pk: true },
      { key: 'route_id',      label: 'Route ID',     fk: true },
      { key: 'source',        label: 'Source' },
      { key: 'destination',   label: 'Destination' },
      { key: 'vehicle_no',    label: 'Vehicle',      mono: true },
      { key: 'departure',     label: 'Departure',    mono: true },
      { key: 'arrival',       label: 'Arrival',      mono: true },
      { key: 'fare',          label: 'Fare (₹)',     mono: true },
      { key: 'seats_left',    label: 'Seats Left',   mono: true },
    ],
    fields: [
      { key: 'route_id',   label: 'Route ID',   type: 'number', required: true, hint: 'FK → routes' },
      { key: 'vehicle_id', label: 'Vehicle ID', type: 'number', required: true, hint: 'FK → vehicles' },
      { key: 'departure',  label: 'Departure',  type: 'time',   required: true },
      { key: 'arrival',    label: 'Arrival',    type: 'time',   required: true },
      { key: 'fare',       label: 'Fare (₹)',   type: 'number', required: true },
      { key: 'seats_left', label: 'Seats Left', type: 'number', required: true },
    ],
  },
  passengers: {
    icon: '👤', label: 'Passengers',
    columns: [
      { key: 'passenger_id', label: 'ID',    pk: true },
      { key: 'name',         label: 'Name',  mono: true },
      { key: 'phone',        label: 'Phone', mono: true },
      { key: 'email',        label: 'Email' },
      { key: 'city',         label: 'City' },
      { key: 'created_at',   label: 'Joined' },
    ],
    fields: [
      { key: 'name',  label: 'Full Name', type: 'text',  required: true },
      { key: 'phone', label: 'Phone',     type: 'text',  required: true },
      { key: 'email', label: 'Email',     type: 'email' },
      { key: 'city',  label: 'City',      type: 'text',  required: true },
    ],
  },
  bookings: {
    icon: '🎫', label: 'Bookings',
    columns: [
      { key: 'booking_id',      label: 'ID',            pk: true },
      { key: 'passenger_name',  label: 'Passenger' },
      { key: 'source',          label: 'From' },
      { key: 'destination',     label: 'To' },
      { key: 'departure',       label: 'Departure',     mono: true },
      { key: 'seat_no',         label: 'Seat',          mono: true },
      { key: 'amount',          label: 'Amount (₹)',    mono: true },
      { key: 'status',          label: 'Status',        chip: true },
      { key: 'booked_at',       label: 'Booked At' },
    ],
    fields: [
      { key: 'passenger_id', label: 'Passenger ID', type: 'number', required: true, hint: 'FK → passengers' },
      { key: 'schedule_id',  label: 'Schedule ID',  type: 'number', required: true, hint: 'FK → schedules' },
      { key: 'seat_no',      label: 'Seat No',      type: 'text',   required: true },
      { key: 'status',       label: 'Status',       type: 'select', required: true,
        options: ['confirmed','pending','cancelled'] },
      { key: 'amount',       label: 'Amount (₹)',   type: 'number', required: true },
    ],
  },
  staff: {
    icon: '👷', label: 'Staff',
    columns: [
      { key: 'staff_id',    label: 'ID',        pk: true },
      { key: 'name',        label: 'Name' },
      { key: 'role',        label: 'Role',      chip: true },
      { key: 'vehicle_no',  label: 'Vehicle',   mono: true },
      { key: 'phone',       label: 'Phone',     mono: true },
      { key: 'joined_date', label: 'Joined' },
    ],
    fields: [
      { key: 'name',        label: 'Full Name',   type: 'text',   required: true },
      { key: 'role',        label: 'Role',        type: 'select', required: true,
        options: ['driver','conductor','manager'] },
      { key: 'vehicle_id',  label: 'Vehicle ID',  type: 'number', hint: 'FK → vehicles (optional)' },
      { key: 'phone',       label: 'Phone',       type: 'text',   required: true },
      { key: 'joined_date', label: 'Joined Date', type: 'date',   required: true },
    ],
  },
};
